### ISSUE TITLE
hints not appearing when pane gets focus

### ISSUE THREAD

**Issue by pannet1** [hozza/tmux-hints#1]
this is a great idea. thank you so much for this work.

i am using the following configuration.
`
new-session -s development -n editor -d
split-window -v -p 20 -t development
select-pane -t 1
split-window -h -p 5 -t development
 
send-keys -t development:1.1 'source ~/dotfiles/tmux/tmux-powerline-theme/powerline-theme.tmux;vim' C-m

new-window -n console -t development
send-keys -t development:1.2 '~/dotfiles/tmux/tmux-hints/tmux-hints.sh -p ~/dotfiles/tmux/hints/' C-m

select-window -t development:1
select-pane -t 1
`
i have created the default tmux.txt and it is displaying every time.  as you can see i am sending vim while attaching the above file. even if i exit from the vim session and start another vim session from one of the tmux pane, my vim.txt hint does not appear.

may be, i did not understand the expected behavior correctly. can you please advise how to make tmux-hints show vim hint when i am editing with it.

note: i am using a different location for tmux-hint and the hint file as you can see from my tmux.conf

**Comment by hozza** [comment]
Hmm 🤔 I can't spot what's wrong at first glance - I'll take a deeper look over the next few days.

It may not be related but for info what OS are you running, which terminal emulator and are you tunneling over SSH/MOSH etc?

**Comment by hozza** [comment]
You don't need to explicitly set send keys to tmux-hints, or do any other sort of setup with tmux yourself. 

Just run a stock session and in an a new pane, run tmux-hints as described in the README - it sets everything up for you - when you navigate to a new pane in the same window, it'll show the notes for that program e.g. vim, assuming the hints file exists.

Try running with default config first with a clean tmux config, see if you can get it running that way, then start troubleshooting your custom hint file location etc. 

Other than that, there's not much else I can do to help with the info provided. Best of luck! :)
